
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-09
owner: ucsb-cs156-f24
repo_name: team02-f24-09
pull_requests: [{"author":{"id":"U_kgDOB7-k5A","is_bot":false,"login":"SexyJesusFreak","name":"Nathaniel Mitter"},"headRefName":"54-Articles","number":72,"title":"add articlesFixtures.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/72"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"18-organization","number":70,"title":"added fixture file","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/70"},{"author":{"id":"U_kgDOBt0KgA","is_bot":false,"login":"azhe12345","name":""},"headRefName":"Hongtao-RQ-27","number":69,"title":"update by task 27","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/69"}]
