
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-09
owner: ucsb-cs156-f24
repo_name: team02-f24-09
pull_requests: [{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"21-organization","number":80,"title":"21 organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/80"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"20-organization","number":79,"title":"20 organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/79"},{"author":{"id":"U_kgDOBt0KgA","is_bot":false,"login":"azhe12345","name":""},"headRefName":"Hongtao-RQ-30","number":78,"title":"cp placeholder","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/78"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"48-HelpRequests","number":76,"title":"48 - Added Placeholders for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/76"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"47-HelpRequests","number":75,"title":"47 - HelpRequests - added table","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/75"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"46-HelpRequests","number":74,"title":"46 - Created Form for HelpRequests","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/74"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"19-organization","number":73,"title":"19 organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/73"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"18-organization","number":70,"title":"added fixture file","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/70"}]
