
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-09
owner: ucsb-cs156-f24
repo_name: team02-f24-09
pull_requests: [{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"24-final-organization","number":109,"title":"24 final organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/109"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"23-new-try-organization","number":107,"title":"23 new try organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/107"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"22-new-try-organization","number":106,"title":"22 new try organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/106"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"21-organization","number":80,"title":"21 organization","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/80"}]
