
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-09
owner: ucsb-cs156-f24
repo_name: team02-f24-09
pull_requests: [{"author":{"id":"U_kgDOB7-k5A","is_bot":false,"login":"SexyJesusFreak","name":"Nathaniel Mitter"},"headRefName":"53-Articles","number":71,"title":"53 articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/71"},{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"18-organization","number":70,"title":"added fixture file","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/70"},{"author":{"id":"U_kgDOBtFGRA","is_bot":false,"login":"neil-roy","name":""},"headRefName":"36-MenuItemReview","number":67,"title":"36 menu item review","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/67"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"45-HelpRequests","number":64,"title":"45 - HelpRequests - added HelpRequestsFixtures.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-09/pull/64"}]
